site_name: Pymetrix
site_url: https://anuran-roy.github.io/pymetrix/
repo_url: https://github.com/anuran-roy/pymetrix-python
repo_name: anuran-roy/pymetrix-python

theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
  favicon: images/favicon.ico
  logo: images/starlite-icon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
      
  # palette:
  #   primary: deep-purple

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences


nav: 
    - Home: index.md
    - API Overview: 'api/overview.md'
    - API Methods: 'api/methods.md'